### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by m-byte** [felixheld/photonSDI#1]
Hi,
I was wondering, what the current status of this project is. Is it dead? Or can teh actual code be found somewhere else?

**Comment by felixheld** [comment]
The project is still alive, but currently the code isn't in a releasable state yet. Getting https://github.com/felixheld/AXIOM-photonSDI-hw ready took longer than expected, so I used up the time i had allocated to push this project forward to get the hardware in a reviewable state. Getting photonSDI ready for being published is definitely on my TODO list; currently I have to get some work done on commercial contracts though.

**Comment by m-byte** [comment]
Thanks for the info! Really looking forward to an open SDI implementation.
